network:
  version: 2
  renderer: networkd
  ethernets:
    enp1s0:
      dhcp4: true
    enp7s0:
      dhcp4: no
      addresses: [192.168.1.254/24]
      routes:
      - to: default
        via: 192.168.10.1
      nameservers:
        addresses: [8.8.8.8,8.8.4.4]
